### ISSUE TITLE
Document: Flowchart

### ISSUE THREAD

**Issue by muhamaddafa** [Group3-IF330H/i27studio#17]

**Comment by naufaland** [comment]
[
![Uploading Flowchart Admin i27Studio.png…]()
](url)

**Comment by naufaland** [comment]
Flowchart Admin
![Flowchart Admin i27Studio](https://github.com/Group3-IF330H/i27studio/assets/126582838/c27f4bb5-a4d1-4932-af52-9a6c4a7250bd)
