### ISSUE TITLE
Document: Database design

### ISSUE THREAD

**Issue by muhamaddafa** [Group3-IF330H/i27studio#18]

**Comment by KingAbby** [comment]
![Image](https://github.com/Group3-IF330H/i27studio/assets/110515353/071e94f3-335d-4a89-bff7-0f9b3e49e703)

**Comment by muhamaddafa** [comment]
@KingAbby itu kategori ilangin aja yg di project dibawah gambar. di table nya jg ya

**Comment by KingAbby** [comment]
![Image](https://github.com/Group3-IF330H/i27studio/assets/110515353/524619ae-25d1-4f3d-aa35-d24bba3d7b33)

**Comment by KingAbby** [comment]
loleoeleoelere
